### ISSUE TITLE
Get "expected keyword" error when running grunt jsx, but the jsx command on its own runs fine

### ISSUE THREAD

**Issue by elsigh** [yosuke-furukawa/grunt-jsx#15]
elsigh@elsigh-macbookair:~/src/baseline/static (sexycb) $ grunt jsx
Running "jsx:views" (jsx) task
jsx --output js/jsx/views.js js/views.jsx
[js/views.jsx:6:0] expected keyword: class interface mixin abstract final native __fake__ __export__
base.views.BackboneMixin = {
^

If I just run jsx --output js/jsx/views.js js/views.jsx things are aok.

   jsx: {
      views: {
        src: 'js/views.jsx',
        dest: 'js/jsx/views.js'
      }
    },

**Comment by rdebeasi** [comment]
Is it possible that you're trying to compile Facebook's JSX syntax? I was trying the same thing, but it turns out that this JSX is a totally different language.

https://github.com/jsx/JSX/issues/332

**Comment by sethwklein** [comment]
Yep, that was my problem.

**Comment by babukrishna** [comment]
+1 Any body have any solution for this?

**Comment by rdebeasi** [comment]
Are you attempting to compile Facebook's JSX, rather than the completely different (but similarly named) format that this tool is designed for?

That was the problem that I ran into a while back.
